name: Deploy React App

on: [push]

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
 
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
       node-version: 18.0.0

#    - name: Install Dependencies
#      run: npm install

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
      


#    - name: Install Yarn
#      uses: borales/actions-yarn@v2.0.0 
#      with:
#       cmd: install --force --ignore-engines # will run "yarn install" command

#    - name: Build react app
#      run: yarn build
    
    - name: Install Surge
      run: npm install -g surge

    - run: surge ./build helloesforge-foodyzone.surge.sh --token ${{secrets.SURGE_TOKEN}}
